<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 3.6.0
 * @copyright Copyright (c) 2015, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AutoCancelPlugin.getCronTasks.schedule_cancellation_name'] = "Auto Horario de cancelación";
$lang['AutoCancelPlugin.getCronTasks.schedule_cancellation_desc'] = "Fijar horarios para que periodicamente los servicios sean cancelados.";
?>